from .antecedente import AntecedenteORM
from .condicion_paciente import CondicionPacienteORM
from .direccion import DireccionORM
from .establecimiento import EstablecimientoORM
from .ficha_epidemiologica import FichaEpidemiologicaORM
from .hospitalizacion import HospitalizacionORM
from .paciente import PacienteORM
from .posible_contagiado import PosibleContagiadoORM
from .posible_contagio import PosibleContagioORM
from .registro_clinico import RegistroClinicoORM
from .registro_laboratorio import RegistroLaboratorioORM
