from .antecedente import AntecedenteAdmin
from .condicion_paciente import CondicionPacienteAdmin
from .direccion import DireccionAdmin
from .establecimiento import EstablecimientoAdmin
from .ficha_epidemiologica import FichaEpidemiologicaAdmin
from .hospitalizacion import HospitalizacionAdmin
from .paciente import PacienteAdmin
from .posible_contagiado import PosibleContagiadoAdmin
from .posible_contagio import PosibleContagioAdmin
from .registro_clinico import RegistroClinicoAdmin
from .registro_laboratorio import RegistroLaboratorioAdmin
